- name: Ensure nginx and php-fpm is installed.
  apt:
    name: "{{item}}"
    update_cache: yes
    state: present
  loop:
    - nginx
    - php7.4-fpm

- name: Ensure service is running
  ansible.builtin.service:
    name: "{{item}}"
    state: started
    enabled: yes
  loop:
    - nginx
    - php7.4-fpm

