---
# tasks file for docker
- name: Ensures  dirs exists
  file:
    path: '/opt/prometheus'
    state: directory

- name: Go to the folder and execute command
  command: chdir=/opt/prometheus ls

- name: Install packages that allow apt to be used over HTTPS
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present

- name: Install docker and its dependecies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-docker
    - python3-pip

- name: Add my user to docker group
  user:
    name: seruff
    group: docker

- name: Creates directory
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Install docker-compose
  pip:
    name: docker-compose

- name: Install docker-compose
  remote_user: seruff
  get_url:
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Template a file
  template:
    src: docker-compose.yml.j2
    dest: /opt/prometheus/docker-compose.yml
    owner: seruff
    mode: '0644'
# tasks file for container
- name: Create and start services
  community.docker.docker_compose:
    project_src: /opt/prometheus
