---
- hosts : vm1-db-u
  become: yes
  tasks:
  - name: ensure prequest is installed
    apt:
      name          : "{{item}}"
      update_cache  : yes
      state         : latest
    loop:
      - openjdk-11-jdk
      - ansible
      -
  - name: Download agent.jar
    get_url:
      url: http://91.203.226.40/jnlpJars/agent.jar
      dest: ~/
      mode: '0640'
  - name: Create a directory if it does not exist

    ansible.builtin.file:
      path: /export/home/jenkins/
      state: directory
      recurse: yes
      mode: '0740'

  - name: Run command
    ansible.builtin.command:
      cmd: java -jar agent.jar -jnlpUrl http://91.203.226.40/computer/vm1/jenkins-agent.jnlp -secret 7fd5ef5a0c554adf445f671444860589bc69ea9ec62779a401d5c3ac0ed15f8f -workDir "/export/home/jenkins"